package com.automation.emailer;


import lombok.Data;

@Data
public class HTMLInteractions {

	private GlobalPOJO globalPOJO;
	private String endLabel = "<br><br>&nbsp&nbsp&nbsp&nbsp<center><b>This Email is Auto Generated by The Conga Automation Framework</b></center>";
	private String lineBreaker = "<br>";
	private String pieChartString = "<center><img src=\"cid:piechart\"></center><br><br>";
	private String barChartString = "<center><img src=\"cid:barchart\"></center><br><br>";
	private String executionBreakUpString = "<center><b><u> Execution Break up for this run is:</u></b></center><br>";
	
	public HTMLInteractions(GlobalPOJO globalPOJO) {
		this.globalPOJO = globalPOJO;
	}

	public String getGreetings() {
		try {
			return "&nbsp&nbsp&nbsp&nbspHi All, <br><br>" + "&nbsp&nbsp&nbsp&nbspThe Automation Execution for the  <b>"
					+ globalPOJO.getProjectName().toUpperCase() + " project</b> has completed today."
					+ "<br><br>&nbsp&nbsp&nbsp&nbspThe CI link for this run is : " + "<a href=\""
					+ globalPOJO.getJenkinsUrl() + "\"style=\"color:#2b7488\">Jenkins URL</a> <br><br>"
					+ "<br>&nbsp&nbsp&nbsp&nbspThe Details for this run is: <br><br>";

		} catch (Exception e) {
			return "Hi All, <br><br>&nbsp&nbsp&nbsp&nbspThe Automation Execution for this project is completed. <br><br>\r\n"
					+ "&nbsp&nbsp&nbsp&nbspThe Details for this run is: <br><br>";
		}

	}

	public String getSummary() {
		try {
			return "<center><b>" + "Today's run was performed with <u>" + globalPOJO.getBrowserName()
					+ "</u> Browser. A total of <u>" + globalPOJO.getTotalPassed() + " tests</u> passed, <u>"
					+ globalPOJO.getTotalFailed() + " tests</u> that failed and <u>" + globalPOJO.getTotalSkipped()
					+ " tests</u> that skipped." + "</b></center><br>";
		} catch (Exception e) {
			return "Today's run is completed. Currently I am unable to populate summary data<br>";
		}
	}

}
